### ISSUE TITLE
[Bug]titleの表記がtileになってる

### ISSUE THREAD

**Issue by tmrkw1497** [miraikeitai2020/backend-bff#51]
**何が問題か？ その説明**  
クエリにタイポがあったので直してもらいたい。  
緊急性はないですが少し気になります…

**解決方法・手法**  
`production.graphql`にある
```
type ArticleInfo {
    tile: String!
    imagePath: String!
    nice: Int!
    context: String!
    userStatus: ArticleUserInfo
    comment: [Comment]
}
```
のtileをtitleに変更する(多分)。  
`backend-bff/pkg/server/resolver/production.go`の変更も必要そう(363行目)。

**他に検討した手段**  
バグを黙認する(仕様だと自分に言い聞かせる)。

**Comment by SaKu2110** [comment]
おー修正する
