### ISSUE TITLE
[Bug] Queryのarticlesがドキュメントの仕様と少し違う

### ISSUE THREAD

**Issue by tmrkw1497** [miraikeitai2020/backend-bff#56]
**何が問題か？ その説明**  
`articles`クエリの`year`と`month`が必須になっている(backend-bff/production.graphqlの151行)。  
これだと年代と月が入力されていない(初期状態)の際にクライアント側で適当な値を入れる必要がある(何を入れればいいのかわからない)。

**解決方法・手法**  
 `articles`クエリの`year`と`month`を必須にしないようにする  。
`backend-bff/production.graphql`を書き換える必要ありそう。  
この場合`backend-bff/pkg/server/resolver/production.go`の325行目も書き換える必要ありそう。

**他に検討した手段**  
もう一つフィルターを使わない時のクエリを用意する。

**Comment by SaKu2110** [comment]
`year`と`month`をnull許容にします
