### ISSUE TITLE
[bug] リスト取得のクエリでarticleIDが要求される

### ISSUE THREAD

**Issue by tmrkw1497** [miraikeitai2020/backend-bff#57]
**何が問題か？ その説明**  
リスト取得のクエリでarticleIDが引数になっている(ドキュメントと異なる実装になっている(本来はtoken送るだけ))。  
なんのarticleID送ればいいのかわからない。

**解決方法・手法**  
`backend-bff/production.graphql`の151行目のarticleidを削除する。  
`backend-bff/pkg/server/resolver/production.go`の278行目の引数も変更する必要あり。

**他に検討した手段**  
適当なarticleidを引数に渡す。  
articleidは必須ではないので無視する。

**Comment by SaKu2110** [comment]
んーRe:snsのWebAPI設計にArticleID書いてるからなぁ
たけちゃんに確認とってみるか
**参考**
[Resnsフロント](https://docs.google.com/document/d/1K7342x315v4enA41_vtjua4qRMQU83kFTBiT8GmKl8g/edit)

**Comment by tmrkw1497** [comment]
> んーRe:snsのWebAPI設計にArticleID書いてるからなぁ
> たけちゃんに確認とってみるか
> **参考**
> [Resnsフロント](https://docs.google.com/document/d/1K7342x315v4enA41_vtjua4qRMQU83kFTBiT8GmKl8g/edit)

ArticleIDが必要なのはリストの追加と削除で、リストの取得はtokenだけになってる([Resnsフロント](https://docs.google.com/document/d/1K7342x315v4enA41_vtjua4qRMQU83kFTBiT8GmKl8g/edit)にも書いてる(ユーザーのリストの情報を送信のところ))。

**Comment by SaKu2110** [comment]
はい、見落としてました...

**Comment by tmrkw1497** [comment]
> はい、見落としてました...

修正ゆっくりで大丈夫
